fix app cicd

diff --git a/.github/workflows/app.yaml b/.github/workflows/app.yaml
--- a/.github/workflows/app.yaml
+++ b/.github/workflows/app.yaml
@@ -33,7 +33,9 @@ jobs:
     # 1️⃣ Set image tag
     # ------------------------------
     - name: Set image tag
-      run: echo "SHORT_HASH=$(git rev-parse --short HEAD)" >> $GITHUB_ENV
+      run: |
+        echo "SHORT_HASH=$(git rev-parse --short HEAD)"
+        echo "SHORT_HASH=$(git rev-parse --short HEAD)" >> $GITHUB_ENV
 
     # ------------------------------
     # 2️⃣ Build and push Docker image
@@ -44,6 +46,7 @@ jobs:
         docker build -t ${{ secrets.DOCKER_USERNAME }}/latency-app:$SHORT_HASH .
         docker tag ${{ secrets.DOCKER_USERNAME }}/latency-app:$SHORT_HASH ${{ secrets.DOCKER_USERNAME }}/latency-app:latest
         echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
+        echo -e "docker push ${{ secrets.DOCKER_USERNAME }}/latency-app:$SHORT_HASH"
         docker push ${{ secrets.DOCKER_USERNAME }}/latency-app:$SHORT_HASH
 
     # ------------------------------
@@ -93,13 +96,16 @@ jobs:
         --instance-id "$INSTANCE_ID" \
         --query "StandardOutputContent" \
         --output text)
-        
+
+        echo "PREVIOUS_IMAGE=$PREVIOUS_IMAGE"
         echo "PREVIOUS_IMAGE=$PREVIOUS_IMAGE" >> $GITHUB_ENV
 
         # Check if empty → first deploy
         if [ -z "$PREVIOUS_IMAGE" ]; then
+          echo "FIRST_DEPLOY=true"
           echo "FIRST_DEPLOY=true" >> $GITHUB_ENV
         else
+          echo "FIRST_DEPLOY=false"
           echo "FIRST_DEPLOY=false" >> $GITHUB_ENV
         fi
 
@@ -108,10 +114,44 @@ jobs:
     # ------------------------------
     - name: Deploy new image
       run: |
-        aws ssm send-command \
+        COMMAND_ID=$(aws ssm send-command \
           --targets "Key=instanceIds,Values=$INSTANCE_ID" \
           --document-name "AWS-RunShellScript" \
-          --parameters 'commands=["docker pull ${{ secrets.DOCKER_USERNAME }}/latency-app:$SHORT_HASH && docker stop latency-app || true && docker rm latency-app || true && docker run -d --name latency-app -p 5000:5000 ${{ secrets.DOCKER_USERNAME }}/latency-app:$SHORT_HASH"]'
+          --parameters 'commands=["docker pull '"${{ secrets.DOCKER_USERNAME }}"'/latency-app:'"$SHORT_HASH"' && docker stop latency-app || true && docker rm latency-app || true && docker run -d --name latency-app -p 5000:5000 '"${{ secrets.DOCKER_USERNAME }}"'/latency-app:'"$SHORT_HASH"'"]' \
+          --query "Command.CommandId" \
+          --output text)
+
+        echo "Sent command. ID=$COMMAND_ID"
+
+        while true; do
+          STATUS=$(aws ssm get-command-invocation \
+            --command-id "$COMMAND_ID" \
+            --instance-id "$INSTANCE_ID" \
+            --query "Status" --output text)
+
+          echo "Current status: $STATUS"
+          if [ "$STATUS" = "Success" ] || [ "$STATUS" = "Failed" ]; then
+            break
+          fi
+          sleep 2
+        done
+
+        OUTPUT=$(aws ssm get-command-invocation \
+          --command-id "$COMMAND_ID" \
+          --instance-id "$INSTANCE_ID" \
+          --query "StandardOutputContent" \
+          --output text)
+
+        ERROR_OUTPUT=$(aws ssm get-command-invocation \
+          --command-id "$COMMAND_ID" \
+          --instance-id "$INSTANCE_ID" \
+          --query "StandardErrorContent" \
+          --output text)
+
+        echo "--- STDOUT ---"
+        echo "$OUTPUT"
+        echo "--- STDERR ---"
+        echo "$ERROR_OUTPUT"
 
     # ------------------------------
     # 7️⃣ Validate deployment & rollback
