fix app cicd

diff --git a/.github/workflows/app.yaml b/.github/workflows/app.yaml
--- a/.github/workflows/app.yaml
+++ b/.github/workflows/app.yaml
@@ -187,21 +187,47 @@ jobs:
           # ------------------------------
           # Create or update service
           # ------------------------------
+            
           if [ -z "$SERVICE_EXISTS" ]; then
             echo "Service does not exist. Creating..."
-            aws ssm send-command \
+            COMMAND_ID=$(aws ssm send-command \
               --targets "Key=instanceIds,Values=$INSTANCE_ID" \
               --document-name "AWS-RunShellScript" \
-              --parameters 'commands=["docker service create --name latency-app --replicas 2 -p 5000:5000 -e TARGET_HOST='"$TARGET_IP"' '"${{ secrets.DOCKER_USERNAME }}"'/latency-app:'"$SHORT_HASH"'"]' \
-              --query "Command.CommandId" --output text
+              --parameters 'commands=["docker service create --name latency-app --replicas 2 -p 5000:5000 -e TARGET_HOST='"$TARGET_IP"' '"***"'/latency-app:'"$SHORT_HASH"'"]' \
+              --query "Command.CommandId" --output text)
           else
             echo "Service exists. Updating..."
-            aws ssm send-command \
+            COMMAND_ID=$(aws ssm send-command \
               --targets "Key=instanceIds,Values=$INSTANCE_ID" \
               --document-name "AWS-RunShellScript" \
-              --parameters 'commands=["docker service update --image '"${{ secrets.DOCKER_USERNAME }}"'/latency-app:'"$SHORT_HASH"' --replicas 2 --update-parallelism 1 --update-delay 5s latency-app"]' \
-              --query "Command.CommandId" --output text
+              --parameters 'commands=["docker service update --image '"***"'/latency-app:'"$SHORT_HASH"' --replicas 2 --update-parallelism 1 --update-delay 5s latency-app"]' \
+              --query "Command.CommandId" --output text)
           fi
+
+          # ✅ Chờ command chạy xong
+          while true; do
+            STATUS=$(aws ssm get-command-invocation \
+              --command-id "$COMMAND_ID" \
+              --instance-id "$INSTANCE_ID" \
+              --query "Status" --output text)
+
+            echo "Command status: $STATUS"
+
+            case "$STATUS" in
+              Success)
+                echo "Command completed successfully ✅"
+                break
+                ;;
+              Failed|Cancelled|TimedOut)
+                echo "Command failed with status $STATUS ❌"
+                exit 1
+                ;;
+              *)
+                echo "Still running... waiting 5s"
+                sleep 5
+                ;;
+            esac
+          done
       
           # ------------------------------
           # Poll rollout status
